// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.


const findTheDifference = function(s, t) {
  s = s.split``.sort().join``;
  t = t.split``.sort().join``;

  for (let i = 0; i < s.length; i++) {
    if (s[i] !== t[i]) {
      return t[i];
    }
  }

  return t[t.length - 1];
};

console.log(findTheDifference('abcd', 'abcde'));
console.log(findTheDifference('abcd', 'abecd'));
